<?php

namespace app\models;

use app\core\Application;
use app\core\DbModel;
use app\core\Model;
use app\core\UserModel;
use PDO;

class User extends UserModel

{
    const STATUS_INACTIVE = 0;
    const STATUS_ACTIVE = 1;
    const STATUS_DELETED = 2;


    public string $firstname = '';
    public string $lastname = '';
    public string $email = '';
    public string $password = '';
    public int $status = self::STATUS_INACTIVE;
    public string $confirmPassword = '';

    public function tableName():string
    {
        return 'users';
    }
    public function attributes(): array
    {
        // TODO: Implement attributes() method.
        return ['firstname', 'lastname', 'email','password', 'status'];
    }

    public function primaryKey():string
    {
        return 'id';
    }

   public function save()
   {
       $this->status = self::STATUS_INACTIVE;
       $this->password = password_hash($this->password, PASSWORD_DEFAULT);
       return parent::save(); // TODO: Change the autogenerated stub
   }

    public function rules(): array
    {
        return [
            'firstname' => [self::RULE_REQUIRED],
            'lastname' => [self::RULE_REQUIRED],
            'email' => [self::RULE_REQUIRED, self::RULE_EMAIL,[self::RULE_UNIQUE, 'class'=>self::class]],
            'password' => [self::RULE_REQUIRED,
                [self::RULE_MIN, 'min'=>8], [self::RULE_MAX, 'max'=>24]],
            'confirmPassword' => [self::RULE_REQUIRED,
                [self::RULE_MATCH, 'match'=>'password']]
        ];
    }

    public function labels(): array
    {
        return[
            'firstname' => 'First name',
            'lastname' => 'Last name',
            'email' => 'Email',
            'password' => 'Password',
            'confirmPassword' => 'Confirm password'
        ];
    }

    public function getDisplayName():string
    {
        return $this->firstname.' '.$this->lastname;
    }
    public function getAdmin($id): bool
    {
        // TODO: Implement getAdmin() method.
        $tableName = $this->tableName();
        $statement = Application::$app->db->pdo->query("SELECT isAdmin FROM $tableName WHERE id=$id");
        $user = $statement->fetch(PDO::FETCH_NUM);
//        echo '<pre>';
//        var_dump($user[0]);
//        echo '</pre>';
//        exit;
        return $user[0];
    }

}